version: '3.8'

services:
  llm:
    gpus: all
    build: ./llm
    container_name: vibe_llm
    volumes:
      - ./llm:/app
    ports:
      - "5555:5555"

  grader:
    build: ./grader
    container_name: vibe_grader
    volumes:
      - ./grader:/app
    ports:
      - "5556:5556"

  backend:
    build: ./backend
    container_name: vibe_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: vibe_frontend
    volumes:
      - ./frontend:/app
      -  vibe_frontend_modules:/app/node_modules
    ports:
      - "5173:5173"

  db:
    image: postgres:14
    container_name: vibe_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - vibe_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  vibe_postgres_data:
  vibe_frontend_modules:
